// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DeliveryBro.Models
{
    public partial class AdministerTable
    {
        public string AdministerAccount { get; set; }
        public string AdministerPassword { get; set; }
        public Guid AdministerId { get; set; }
    }
}