// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DeliveryBro.Models
{
    public partial class CouponTable
    {
        public int CouponId { get; set; }
        public int? CouponDiscount { get; set; }
        public string CouponName { get; set; }
        public TimeSpan? CouponTimeStart { get; set; }
        public TimeSpan? CouponTimeEnd { get; set; }
        public string CouponLimit { get; set; }
        public string CouponDesription { get; set; }
        public byte[] CouponPicture { get; set; }
        public int CouponCount { get; set; }
    }
}