// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DeliveryBro.Models
{
    public partial class CustomerAddressTable
    {
        public int CustomerAddressId { get; set; }
        public int CustomerId { get; set; }
        public string CustomerAddress { get; set; }

        public virtual CustomersTable Customer { get; set; }
    }
}