// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace DeliveryBro.Models
{
    public partial class OrderDetailsTable
    {
        public int OrderId { get; set; }
        public int DishId { get; set; }
        public DateTime OrderDate { get; set; }
        public int UnitPrice { get; set; }
        public int Quantity { get; set; }
        public int Subtotal { get; set; }
        public int? Discount { get; set; }
        public int Total { get; set; }
        public string DishName { get; set; }

        public virtual CustomerOrderTable Order { get; set; }
    }
}